//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringResourceLocalization.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringResourceLocalization.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code never lies, comments sometimes do..
        /// </summary>
        public static string CodeNeverLies {
            get {
                return ResourceManager.GetString("CodeNeverLies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ethernet always wins..
        /// </summary>
        public static string EthernetWins {
            get {
                return ResourceManager.GetString("EthernetWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First, solve the problem. Then, write the code..
        /// </summary>
        public static string FirstSolve {
            get {
                return ResourceManager.GetString("FirstSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello, World!.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Measuring programming progress by lines of code is like measuring aircraft building progress by weight..
        /// </summary>
        public static string MeasuringProgress {
            get {
                return ResourceManager.GetString("MeasuringProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software gets slower faster than hardware gets faster..
        /// </summary>
        public static string SoftwareSlower {
            get {
                return ResourceManager.GetString("SoftwareSlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a When in doubt, reboot..
        /// </summary>
        public static string WhenInDoubt {
            get {
                return ResourceManager.GetString("WhenInDoubt", resourceCulture);
            }
        }
    }
}
